import type { AssessmentAnswers } from "@/types/assessment";

/** Priya — salaried professional, prime credit, comfortable borrow scenario */
export const priyaFixture: AssessmentAnswers = {
  loanPurpose: "home-renovation",
  amountWanted: 400_000,
  loanProductType: "unsecured-pl",
  employmentType: "salaried",
  netMonthlyIncome: 85_000,
  existingMonthlyEmis: 12_000,
  monthlyHouseholdExpenses: 35_000,
  age: 32,
  creditScore: 780,
  employerTenureMonths: 36,
  incomeStability: "fixed",
  yearsInBusiness: null,
  itrIncome: null,
  cashIncomeEstimate: null,
  ownsCollateral: null,
  collateralValue: null,
  incomeMin: null,
  incomeMax: null,
  platformSourceCount: null,
  hasHighCostDebt: null,
  bouncedPaymentsLast6Months: null,
  emergencySavingsMonths: 4,
  pastBouncedPayments: false,
  cardUtilizationPercent: 25,
  upcomingLargeExpenses: null,
  loanProductivityReturn: null,
  lenderOfferRate: 13.5,
  lenderOfferAmount: 400_000,
  lenderOfferTenureMonths: 36,
  hasCoBorrower: null,
  coBorrowerIncome: null,
  incomeNegativeShock: false,
  dependents: 1,
  skippedFields: [],
};

/** Ravi — self-employed shop owner, large loan, collateral available */
export const raviFixture: AssessmentAnswers = {
  loanPurpose: "business",
  amountWanted: 800_000,
  loanProductType: "business-loan",
  employmentType: "self-employed",
  netMonthlyIncome: null,
  existingMonthlyEmis: 18_000,
  monthlyHouseholdExpenses: 40_000,
  age: 41,
  creditScore: 720,
  employerTenureMonths: null,
  incomeStability: null,
  yearsInBusiness: 8,
  itrIncome: 95_000,
  cashIncomeEstimate: 130_000,
  ownsCollateral: true,
  collateralValue: 2_500_000,
  incomeMin: null,
  incomeMax: null,
  platformSourceCount: null,
  hasHighCostDebt: null,
  bouncedPaymentsLast6Months: null,
  emergencySavingsMonths: 2,
  pastBouncedPayments: false,
  cardUtilizationPercent: 45,
  upcomingLargeExpenses: 100_000,
  loanProductivityReturn: 25_000,
  lenderOfferRate: 14.0,
  lenderOfferAmount: 800_000,
  lenderOfferTenureMonths: 48,
  hasCoBorrower: false,
  coBorrowerIncome: null,
  incomeNegativeShock: false,
  dependents: 2,
  skippedFields: [],
};

/** Anita — informal/gig worker, stretch scenario with some risk flags */
export const anitaFixture: AssessmentAnswers = {
  loanPurpose: "personal",
  amountWanted: 150_000,
  loanProductType: "unsecured-pl",
  employmentType: "informal",
  netMonthlyIncome: null,
  existingMonthlyEmis: 8_000,
  monthlyHouseholdExpenses: 18_000,
  age: 28,
  creditScore: "unknown",
  employerTenureMonths: null,
  incomeStability: null,
  yearsInBusiness: null,
  itrIncome: null,
  cashIncomeEstimate: null,
  ownsCollateral: null,
  collateralValue: null,
  incomeMin: 22_000,
  incomeMax: 35_000,
  platformSourceCount: 2,
  hasHighCostDebt: true,
  bouncedPaymentsLast6Months: false,
  emergencySavingsMonths: 1,
  pastBouncedPayments: false,
  cardUtilizationPercent: 70,
  upcomingLargeExpenses: null,
  loanProductivityReturn: null,
  lenderOfferRate: 22.0,
  lenderOfferAmount: 150_000,
  lenderOfferTenureMonths: 24,
  hasCoBorrower: null,
  coBorrowerIncome: null,
  incomeNegativeShock: false,
  dependents: 0,
  skippedFields: ["cardUtilizationPercent"],
};

export const anitaDistressFixture: AssessmentAnswers = {
  ...anitaFixture,
  bouncedPaymentsLast6Months: true,
  pastBouncedPayments: true,
  hasHighCostDebt: true,
  incomeNegativeShock: true,
};
