import type { AssessmentAnswers, EmploymentType, IncomeStability, LoanPurpose, LoanProductType } from "@/types/assessment";
import { LARGE_LOAN_THRESHOLD } from "@/config/constants";

export type QuestionInputType =
  | "select"
  | "number"
  | "radio"
  | "boolean"
  | "creditScore";

export interface QuestionDefinition {
  id: keyof AssessmentAnswers & string;
  category: string;
  label: string;
  description: string;
  whyAsk?: string;
  inputType: QuestionInputType;
  skippable: boolean;
  required: boolean;
  visible?: (answers: AssessmentAnswers) => boolean;
  options?: { value: string; label: string; description?: string }[];
  placeholder?: string;
  min?: number;
  max?: number;
  step?: number;
  supportsUnknown?: boolean;
}

export const QUESTION_LABELS: Record<string, string> = {
  loanPurpose: "Loan purpose",
  amountWanted: "Requested amount",
  loanProductType: "Product type",
  age: "Age",
  employmentType: "Employment type",
  netMonthlyIncome: "Monthly income",
  employerTenureMonths: "Employer tenure",
  incomeStability: "Income stability",
  itrAnnualIncome: "ITR annual income",
  cashIncomeEstimate: "Cash income estimate",
  yearsInBusiness: "Years in business",
  ownsCollateral: "Collateral ownership",
  collateralValue: "Collateral value",
  incomeMin: "Minimum monthly income",
  incomeMax: "Maximum monthly income",
  platformSourceCount: "Income sources",
  hasHighCostDebt: "High-cost debt",
  bouncedPaymentsLast6Months: "Recent bounced payments",
  existingMonthlyEmis: "Existing EMIs",
  monthlyHouseholdExpenses: "Household expenses",
  creditScore: "Credit score",
  emergencySavingsMonths: "Emergency savings",
  pastBouncedPayments: "Past bounced payments",
  cardUtilizationPercent: "Credit card utilization",
  upcomingLargeExpenses: "Upcoming expenses",
  loanProductivityReturn: "Expected loan return",
  lenderOfferRate: "Lender offer rate",
  lenderOfferAmount: "Lender offer amount",
  lenderOfferTenureMonths: "Lender offer tenure",
  incomeNegativeShock: "Income shock",
  dependents: "Dependents",
};

const LOAN_PURPOSES: { value: LoanPurpose; label: string }[] = [
  { value: "personal", label: "Personal expenses" },
  { value: "home-renovation", label: "Home renovation" },
  { value: "business", label: "Business" },
  { value: "education", label: "Education" },
  { value: "medical", label: "Medical" },
  { value: "debt-consolidation", label: "Debt consolidation" },
  { value: "other", label: "Other" },
];

const LOAN_PRODUCTS: { value: LoanProductType; label: string }[] = [
  { value: "unsecured-pl", label: "Personal Loan (unsecured)" },
  { value: "secured-lap", label: "Loan Against Property" },
  { value: "gold-loan", label: "Gold Loan" },
  { value: "business-loan", label: "Business Loan" },
];

const EMPLOYMENT_OPTIONS: { value: EmploymentType; label: string; description: string }[] = [
  { value: "salaried", label: "Salaried", description: "Fixed monthly salary from employer" },
  { value: "self-employed", label: "Self-employed", description: "Business owner or professional" },
  { value: "informal", label: "Informal / Gig", description: "Platform work, cash income, freelance" },
];

export function shouldShowCollateralQuestions(answers: AssessmentAnswers): boolean {
  return (
    answers.employmentType === "self-employed" &&
    (answers.amountWanted ?? 0) > LARGE_LOAN_THRESHOLD
  );
}

export const ALL_QUESTIONS: QuestionDefinition[] = [
  {
    id: "loanPurpose",
    category: "Your Loan",
    label: "What is the loan for?",
    description: "Purpose helps us understand whether the loan supports essential needs or optional spending.",
    whyAsk: "Loan purpose affects how strictly we treat affordability — essential needs get more conservative guidance.",
    inputType: "select",
    skippable: false,
    required: true,
    options: LOAN_PURPOSES.map((p) => ({ value: p.value, label: p.label })),
  },
  {
    id: "amountWanted",
    category: "Your Loan",
    label: "How much do you want to borrow?",
    description: "Enter the amount you plan to request from the lender.",
    whyAsk: "We compare your requested amount against both borrower-safe and lender-side capacity.",
    inputType: "number",
    skippable: false,
    required: true,
    placeholder: "e.g. 500000",
    min: 10000,
  },
  {
    id: "loanProductType",
    category: "Your Loan",
    label: "What type of loan are you considering?",
    description: "Product type affects rate bands and collateral requirements.",
    inputType: "select",
    skippable: false,
    required: true,
    options: LOAN_PRODUCTS.map((p) => ({ value: p.value, label: p.label })),
  },
  {
    id: "age",
    category: "About You",
    label: "What is your age?",
    description: "Age affects tenure options lenders typically offer.",
    inputType: "number",
    skippable: false,
    required: true,
    placeholder: "e.g. 32",
    min: 18,
    max: 70,
  },
  {
    id: "employmentType",
    category: "About You",
    label: "How do you earn your income?",
    description: "Your employment type determines which affordability rules apply.",
    whyAsk: "Salaried, self-employed, and informal earners face different FOIR caps and rate bands.",
    inputType: "radio",
    skippable: false,
    required: true,
    options: EMPLOYMENT_OPTIONS.map((o) => ({
      value: o.value,
      label: o.label,
      description: o.description,
    })),
  },
  {
    id: "netMonthlyIncome",
    category: "Your Income",
    label: "What is your monthly take-home income?",
    description: "This helps us estimate how much EMI your current cash flow can safely support.",
    whyAsk: "Your lender may calculate affordability differently from what is comfortable for your household.",
    inputType: "number",
    skippable: false,
    required: true,
    placeholder: "Take-home after tax",
    min: 1,
    visible: (a) => a.employmentType === "salaried",
  },
  {
    id: "employerTenureMonths",
    category: "Your Income",
    label: "How long have you been with your current employer?",
    description: "Longer tenure signals income stability to lenders.",
    inputType: "number",
    skippable: true,
    required: false,
    placeholder: "e.g. 24",
    min: 0,
    visible: (a) => a.employmentType === "salaried",
  },
  {
    id: "incomeStability",
    category: "Your Income",
    label: "How stable is your monthly income?",
    description: "Variable income affects how much EMI buffer we recommend.",
    inputType: "select",
    skippable: true,
    required: false,
    visible: (a) => a.employmentType === "salaried",
    options: [
      { value: "fixed", label: "Mostly fixed" },
      { value: "variable", label: "Mostly variable" },
      { value: "mixed", label: "Mixed" },
    ],
  },
  {
    id: "itrAnnualIncome",
    category: "Your Income",
    label: "What is your annual income shown in your ITR?",
    description: "Annual income as declared in your Income Tax Return — we convert this to a monthly figure.",
    whyAsk: "Lenders rely on verifiable ITR income for self-employed borrowers, not cash estimates.",
    inputType: "number",
    skippable: false,
    required: true,
    placeholder: "Annual income from ITR",
    min: 1,
    visible: (a) => a.employmentType === "self-employed",
  },
  {
    id: "cashIncomeEstimate",
    category: "Your Income",
    label: "What is your estimated monthly cash income?",
    description: "Unverifiable cash component — used only when ITR income is unavailable.",
    inputType: "number",
    skippable: true,
    required: false,
    placeholder: "Cash not in ITR",
    min: 0,
    visible: (a) => a.employmentType === "self-employed",
  },
  {
    id: "yearsInBusiness",
    category: "Your Income",
    label: "How many years have you been in business?",
    description: "Business vintage affects lender confidence in your income.",
    inputType: "number",
    skippable: true,
    required: false,
    placeholder: "e.g. 5",
    min: 0,
    visible: (a) => a.employmentType === "self-employed",
  },
  {
    id: "ownsCollateral",
    category: "Collateral",
    label: "Do you own unencumbered property or collateral?",
    description: "Collateral may unlock a lower-cost secured loan route.",
    whyAsk: "Sufficient collateral can shift routing from unsecured to secured products with better rates.",
    inputType: "boolean",
    skippable: true,
    required: false,
    visible: shouldShowCollateralQuestions,
  },
  {
    id: "collateralValue",
    category: "Collateral",
    label: "What is the estimated collateral value?",
    description: "Approximate market value of property or asset you can pledge.",
    inputType: "number",
    skippable: true,
    required: false,
    placeholder: "e.g. 2500000",
    min: 1,
    visible: (a) => shouldShowCollateralQuestions(a) && a.ownsCollateral === true,
  },
  {
    id: "incomeMin",
    category: "Your Income",
    label: "What is your minimum monthly income?",
    description: "Low end of your typical monthly earnings from gig/platform work.",
    inputType: "number",
    skippable: false,
    required: true,
    placeholder: "Lowest month",
    min: 1,
    visible: (a) => a.employmentType === "informal",
  },
  {
    id: "incomeMax",
    category: "Your Income",
    label: "What is your maximum monthly income?",
    description: "High end of your typical monthly earnings.",
    inputType: "number",
    skippable: false,
    required: true,
    placeholder: "Best month",
    min: 1,
    visible: (a) => a.employmentType === "informal",
  },
  {
    id: "platformSourceCount",
    category: "Your Income",
    label: "How many income sources do you have?",
    description: "More sources can mean more volatility but also diversification.",
    inputType: "number",
    skippable: true,
    required: false,
    placeholder: "Platforms / clients",
    min: 1,
    visible: (a) => a.employmentType === "informal",
  },
  {
    id: "hasHighCostDebt",
    category: "Obligations",
    label: "Do you have any high-cost debt (>24% APR)?",
    description: "App loans, credit cards, or informal loans at very high rates.",
    inputType: "boolean",
    skippable: true,
    required: false,
    visible: (a) => a.employmentType === "informal",
  },
  {
    id: "bouncedPaymentsLast6Months",
    category: "Obligations",
    label: "Any bounced payments in the last 6 months?",
    description: "Recent payment failures are a strong distress signal.",
    inputType: "boolean",
    skippable: true,
    required: false,
    visible: (a) => a.employmentType === "informal",
  },
  {
    id: "existingMonthlyEmis",
    category: "Obligations",
    label: "What are your total existing monthly EMIs?",
    description: "Include all loan EMIs — personal, home, vehicle, etc.",
    whyAsk: "Existing obligations reduce how much new EMI your cash flow can safely absorb.",
    inputType: "number",
    skippable: false,
    required: true,
    placeholder: "All EMIs combined",
    min: 0,
  },
  {
    id: "monthlyHouseholdExpenses",
    category: "Household",
    label: "What are your monthly household expenses?",
    description: "Rent, food, utilities, school fees, and other regular household costs.",
    whyAsk: "We use this to estimate a borrower-safe EMI rather than only the maximum amount a lender may approve.",
    inputType: "number",
    skippable: false,
    required: true,
    placeholder: "Rent, food, utilities, etc.",
    min: 0,
  },
  {
    id: "creditScore",
    category: "Credit",
    label: "What is your credit score?",
    description: "Your CIBIL or bureau score, if you know it.",
    whyAsk: "Credit score affects your fair rate band — unknown score widens the range but is never treated as bad credit.",
    inputType: "creditScore",
    skippable: true,
    required: false,
    placeholder: "e.g. 780",
    min: 300,
    max: 900,
    supportsUnknown: true,
  },
  {
    id: "emergencySavingsMonths",
    category: "Household",
    label: "How many months of expenses do you have in emergency savings?",
    description: "Liquid savings that could cover household expenses if income drops.",
    inputType: "number",
    skippable: true,
    required: false,
    placeholder: "e.g. 3",
    min: 0,
  },
  {
    id: "dependents",
    category: "Household",
    label: "How many dependents rely on your income?",
    description: "People whose expenses your income supports.",
    inputType: "number",
    skippable: true,
    required: false,
    placeholder: "e.g. 2",
    min: 0,
  },
  {
    id: "pastBouncedPayments",
    category: "Optional",
    label: "Any past bounced payments?",
    description: "Historical payment failures beyond the last 6 months.",
    inputType: "boolean",
    skippable: true,
    required: false,
  },
  {
    id: "cardUtilizationPercent",
    category: "Optional",
    label: "What is your credit card utilization?",
    description: "Percentage of total credit limit currently used.",
    inputType: "number",
    skippable: true,
    required: false,
    placeholder: "e.g. 40",
    min: 0,
    max: 100,
  },
  {
    id: "upcomingLargeExpenses",
    category: "Optional",
    label: "Any upcoming large expenses?",
    description: "Wedding, medical, school fees, or other planned big spends in the next year.",
    whyAsk: "Large upcoming expenses reduce your safe EMI room over the next 12 months.",
    inputType: "number",
    skippable: true,
    required: false,
    placeholder: "Total in ₹",
    min: 0,
  },
  {
    id: "loanProductivityReturn",
    category: "Optional",
    label: "Expected monthly return from this loan?",
    description: "For business loans — expected monthly income the loan will generate.",
    inputType: "number",
    skippable: true,
    required: false,
    visible: (a) => a.employmentType === "self-employed",
    min: 0,
  },
  {
    id: "lenderOfferRate",
    category: "Lender Offer",
    label: "Lender offer rate (% p.a.)",
    description: "If you already have a quote, enter the offered interest rate.",
    inputType: "number",
    skippable: true,
    required: false,
    step: 0.1,
    min: 1,
    max: 40,
  },
  {
    id: "lenderOfferAmount",
    category: "Lender Offer",
    label: "Lender offer amount (₹)",
    description: "Amount the lender has offered to lend.",
    inputType: "number",
    skippable: true,
    required: false,
    min: 10000,
  },
  {
    id: "lenderOfferTenureMonths",
    category: "Lender Offer",
    label: "Lender offer tenure (months)",
    description: "Repayment period in the lender's offer.",
    inputType: "number",
    skippable: true,
    required: false,
    min: 6,
    max: 360,
  },
  {
    id: "incomeNegativeShock",
    category: "Optional",
    label: "Recent income shock (job loss / co-earner loss)?",
    description: "Significant income reduction in the household in the last 3 months.",
    inputType: "boolean",
    skippable: true,
    required: false,
  },
];

export function getQuestionById(id: string): QuestionDefinition | undefined {
  return ALL_QUESTIONS.find((q) => q.id === id);
}
